wishlist.repository.type=mongo

spring.mongodb.host=${DB_HOST:databasedev}
spring.mongodb.port=${DB_PORT:27017}
spring.mongodb.database=${DB_DATABASE:wishlist}
spring.mongodb.username=${DB_USER:admin_user}
spring.mongodb.password=${DB_PASS:Su@S&nh@!@#Fort&!@qu!}
spring.mongodb.authentication-database=admin
spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=\
  org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,\
  org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,\
  org.springframework.boot.data.jpa.autoconfigure.DataJpaRepositoriesAutoConfiguration
