wishlist.repository.type=mongo

spring.mongodb.uri=mongodb://${spring.mongodb.username}:${spring.mongodb.password}@${spring.mongodb.host}:${spring.mongodb.port}/${spring.mongodb.database}?authSource=admin